version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["db"]
    networks:
      - servers
    ports:
      - "8083:8083"

  balancer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["lb", "--trace=true"]
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8080"]
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8080:8080"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8080"]
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8081:8080"

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server", "--port=8080"]
    networks:
      - servers
    depends_on:
      - db
    ports:
      - "8082:8080"

networks:
  servers:
    driver: bridge
