name: CI Pipeline

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: docker-compose -f docker-compose.test.yaml build

      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker-compose.test.yaml up --exit-code-from test

      - name: Shutdown Docker Compose
        run: docker-compose -f docker-compose.test.yaml down